# Generated by Django 3.0 on 2023-01-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.TimeField(auto_created=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_updated', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
